-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

START TRANSACTION;
INSERT INTO `ierdb`.`Users` (`email`, `password`, `first_name`, `last_name`, `type`, `createdAt`, `updatedAt`) VALUES ('sarah.lobser@gmail.com', 'poops', 'Sarah', 'Lobser', 2, 'NOW()', 'NOW()');
INSERT INTO `ierdb`.`Users` (`email`, `password`, `first_name`, `last_name`, `type`, `createdAt`, `updatedAt`) VALUES ('davidsavila@gmail.com', 'david', 'David', 'Avila', 2, 'NOW()', 'NOW()');
INSERT INTO `ierdb`.`Users` (`email`, `password`, `first_name`, `last_name`, `type`, `createdAt`, `updatedAt`) VALUES ('ctuck04@gmail.com', 'colin', 'Colin', 'Tucker', 2, 'NOW()', 'NOW()');

COMMIT;


-- -----------------------------------------------------
-- Data for table `ierdb`.`Products`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `ierdb`.`Products` (`id`, `category`, `price`, `description`, `brand`, `rating`, `name`, `quantity`, `createdAt`, `updatedAt`) VALUES (1, 'After Hours', 65000.00, 'You dance, they salivate', 'Your Momma Adventures', 1, 'Dancing With The Wolf Stars', 22, NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `ierdb`.`Employees`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `ierdb`.`Employees` (`name`, `title`, `email`, `bio`, `createdAt`, `updatedAt`) VALUES ('Erika Miller', 'CFO', 'ErikaM@gmail.com', 'Erika graduated from Harvard in 2000 with a B.S. in business and majoring in accounting. She began her career in the accounting department of Umbrella Corporation. After years of experience she was promoted to a Director role.', NULL, NULL);
INSERT INTO `ierdb`.`Employees` (`name`, `title`, `email`, `bio`, `createdAt`, `updatedAt`) VALUES ('Peter Chestnut', 'CEO', 'PChestnut@gmail.com', 'As CEO Peter is responsible for running all facets of the business. His experience as CEO and CFO of SwiftOlo and WhiteCloud respectively, lend him a proven executive track record. Peter also served as President of Globex Inc.\'s e-commerce division and was recognized by Internet World as one of the top 25 \'Click and Mortar\' executives in the country in June of 2000.', NULL, NULL);
INSERT INTO `ierdb`.`Employees` (`name`, `title`, `email`, `bio`, `createdAt`, `updatedAt`) VALUES ('Michael James', 'Director of Sales', 'MJames@gmail.com', 'After attending the University of Texas, Michael excelled in a sales role for Initech. He then ascended into a managerial role and increasing sales in his division drastically. In 2013 he was given the role of Director of Sales and was nominated for Forbes \'Top 25 Under 25\'.', NULL, NULL);
INSERT INTO `ierdb`.`Employees` (`name`, `title`, `email`, `bio`, `createdAt`, `updatedAt`) VALUES ('Alexandra Bennett', 'Marketing Director', 'AlexandraB@gmail.com', 'With over 20 years experience in international product sales, and applying a strong expertise in data-driven, long-term strategic planning, Alexandra excels in her role as Marketing director. Previous to this, Alexandra held various positions Director of International Sales & Marketing, Manager of Business Development, and Trade Sales Manager for St. Anky Beer.', NULL, NULL);
INSERT INTO `ierdb`.`Employees` (`name`, `title`, `email`, `bio`, `createdAt`, `updatedAt`) VALUES ('David Silver', 'Founder', 'silverfox@gmail.com', 'A native of New York, David graduated from Yale University with an honors degree in economic studies. David is a lifelong entrepreneur, adventurer, and tech aficionado. In 2014 he accepted the award for Most Innovative Startup, by the Inc. 500. David is focused on bringing quality products as well as streamlined experience to his customers. He is an avid traveler and aviation enthusiast, and has lived in Chile as well as Peru.', NULL, NULL);

COMMIT;

-- -----------------------------------------------------
-- Data for table `ierdb`.`Products`
-- -----------------------------------------------------
START TRANSACTION;

INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('skydiving','5999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Air Time','1','Xtreme Single Engine','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('skydiving','5999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Air Time','2','Military insertion','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('skydiving','5999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Air Time','3','HALO','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('skydiving','5999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Air Time','4','Seal Team Six','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('skydiving','5999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Air Time','5','Escape and Evasion','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('skydiving','3999.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Air Time','1','Behind Enemy Lines','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('skydiving','3999.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Air Time','2','Air Drop','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('skydiving','3999.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Air Time','3','Moonraker 101','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('skydiving','3999.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Air Time','4','Tom Cruise Special','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('skydiving','3999.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Air Time','5','Squirrel Suit Extravaganza','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('skydiving','9999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Air Time','1','Hit the target','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('skydiving','9999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Out Of This World','2','Don\'t Go Splat','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('skydiving','9999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Out Of This World','3','Team Jumping for Dummies','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('skydiving','9999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Out Of This World','4','Make Shapes','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('skydiving','9999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Out Of This World','5','Chutes are for wimps','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('skydiving','9999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Out Of This World','1','Mile High club','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('skydiving','9999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Out Of This World','2','Red Light Green Light','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('skydiving','9999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Out Of This World','3','80s Action Movie Special','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('skydiving','9999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Out Of This World','4','Penultimate Experience','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('skydiving','300000.0','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Out Of This World','5','Felix Baumgartner Experience','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('mountaineering','5999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Adventure Consultants','1','Everest','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('mountaineering','5999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Adventure Consultants','2','K2','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('mountaineering','5999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Adventure Consultants','3','Ana Purna','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('mountaineering','5999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Adventure Consultants','4','Denali','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('mountaineering','5999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Adventure Consultants','5','Kilamanjaro','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('mountaineering','3999.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Adventure Consultants','1','Fuji','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('mountaineering','3999.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Adventure Consultants','2','Pikes Peak','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('mountaineering','3999.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Adventure Consultants','3','Matterhorn','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('mountaineering','3999.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Adventure Consultants','4','Eiger','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('mountaineering','3999.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Adventure Consultants','5','Huang','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('mountaineering','9999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Adventure Consultants','1','Kailash','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('mountaineering','9999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Adventure Consultants','2','Fitz Roy','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('mountaineering','9999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Mountain Madness','3','Everest','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('mountaineering','9999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Mountain Madness','4','K2','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('mountaineering','9999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Mountain Madness','5','Ana Purna','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('mountaineering','9999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Mountain Madness','1','Denali','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('mountaineering','9999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Mountain Madness','2','Kilamanjaro','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('mountaineering','9999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Mountain Madness','3','Fuji','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('mountaineering','9999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Mountain Madness','4','Pikes Peak','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('mountaineering','300000.0','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Mountain Madness','5','Banff','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('heli-skiing','19999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Two Rotors No Problems','1','Copper Mountain','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('heli-skiing','19999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Two Rotors No Problems','2','Breckenridge','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('heli-skiing','19999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Two Rotors No Problems','3','Vail','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('heli-skiing','19999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Two Rotors No Problems','4','A-Basin','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('heli-skiing','19999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Two Rotors No Problems','5','Loveland','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('heli-skiing','19999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Two Rotors No Problems','1','Banff','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('heli-skiing','25999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Two Rotors No Problems','2','Matterhorn','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('heli-skiing','25999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Two Rotors No Problems','3','Alps','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('heli-skiing','25999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Two Rotors No Problems','4','Everest','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('heli-skiing','25999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Macready Air','5','K2','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('heli-skiing','25999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Macready Air','1','Denali','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('heli-skiing','13999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Macready Air','2','Antarctica','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('heli-skiing','13999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Macready Air','3','Silverthorne','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('heli-skiing','13999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Macready Air','4','Aspen','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('heli-skiing','13999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Macready Air','5','Gunnison','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('heli-skiing','13999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Macready Air','1','Crested Butte','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('heli-skiing','13999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Macready Air','2','Durango','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('heli-skiing','13999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Macready Air','3','Salida','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('heli-skiing','13999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Macready Air','4','Buena Vista','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('heli-skiing','13999.990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Macready Air','5','Vancouver','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('diving','1999.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Shark Buddies','1','Divestravaganza','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('diving','1999.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Shark Buddies','2','Nuclear Wrecks','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('diving','1999.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Shark Buddies','3','WW2 Wrecks','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('diving','1999.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Shark Buddies','4','Titanic Dive','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('diving','1999.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Shark Buddies','5','Sharktapus Search','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('diving','1999.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Shark Buddies','1','UnderWater Tornado','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('diving','2999.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Shark Buddies','2','Spear Fishing Adventure','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('diving','399.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Shark Buddies','3','Meeting Marlin','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('diving','3999.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Shark Buddies','4','Marianas Trench','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('diving','2999.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Shark Buddies','5','Cuddly Crabs','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('diving','399.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Shark Buddies','1','Loving Lobsters','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('diving','3999.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Shark Buddies','2','Steve Irwin Stingray Experience','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('diving','1999.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Yellow Submariners','3','Saltwater Crocs','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('diving','1999.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Yellow Submariners','4','Avatar: The Phosperecent Origins','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('diving','1999.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Yellow Submariners','5','Coral-copia','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('diving','2999.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Yellow Submariners','1','Deep Water Winning','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('diving','399.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Yellow Submariners','2','Angler Fish Need Love Too','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('diving','3999.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Yellow Submariners','3','Mediteranean Mussels','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('diving','2999.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Yellow Submariners','4','Barbary Coast Halibut Harems','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('diving','399.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Yellow Submariners','5','Pearl Diving in St. Tropez','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('downhill biking','3999.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Inertial Imperative','1','K2 Collision','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('downhill biking','1999.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Inertial Imperative','2','Crashing Crested Butte','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('downhill biking','1999.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Inertial Imperative','3','Forest Fiesta','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('downhill biking','1999.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Inertial Imperative','4','KilamanjaroRace','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('downhill biking','1999.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Inertial Imperative','5','Cecil the Lion Memorial Downhill','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('downhill biking','1999.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Inertial Imperative','1','eXtreme Unicycling','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('downhill biking','1999.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Inertial Imperative','2','Who need two wheels?','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('downhill biking','2999.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Inertial Imperative','3','Tricycle Tots: Toddlers Only','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('downhill biking','399.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Inertial Imperative','4','Tandem Downhill Racing','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('downhill biking','3999.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Inertial Imperative','5','Presidential Time Trial','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('downhill biking','2999.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Inertial Imperative','1','No Brakes Survival Challenge','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('downhill biking','399.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Inertial Imperative','2','Cactus Friends Moab Endurance','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('downhill biking','3999.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Gravity Groupies','3','Endless Summer Cross Country','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('downhill biking','1999.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Gravity Groupies','4','Rock the Rockies','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('downhill biking','1999.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Gravity Groupies','5','AT Endurance Trial','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('downhill biking','1999.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Gravity Groupies','1','PCT Endurance Trial','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('downhill biking','2999.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Gravity Groupies','2','CDT Endurance Trial','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('downhill biking','399.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Gravity Groupies','3','To Hell and Back: Annual Sahara Desert Round Trip Race','5');
INSERT INTO Products (category, price, description, brand, rating, name, quantity) VALUES ('downhill biking','3999.989990234375','Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.','Gravity Groupies','4','Everest Downhill Survival Challenge','5');

COMMIT;
